version: "3"
networks:
  burn-x-network:
volumes:
  burn-x-minio:
    driver: local
  burn-x-mongo:
    driver: local
services:
  mongo:
    image: mongo:6.0.3-focal
    networks:
      - burn-x-network
    volumes:
      - burn-x-mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: super_kolla
      MONGO_INITDB_ROOT_PASSWORD: G2DJXVQtHp3v2yXlOQ
  # minio:
  #   image: minio/minio:RELEASE.2023-05-04T21-44-30Z.fips
  #   networks:
  #     - burn-x-network
  #   ports:
  #     - "9000:9000"
  #     - "9090:9090"
  #   volumes:
  #     - burn-x-minio:/data
  #   environment:
  #     MINIO_ROOT_USER: burn-x-admin
  #     MINIO_ROOT_PASSWORD: wwkSND2Q4vIYU9x
  #   command: server --address 0.0.0.0:9000 --console-address ":9090" /data
  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint:
  #     /bin/sh -c "
  #     /usr/bin/mc alias set myminio http://minio:9000 burn-x-admin wwkSND2Q4vIYU9x;
  #     /usr/bin/mc mb myminio/burn-x;
  #     /usr/bin/mc anonymous set download myminio/burn-x;
  #     exit 0;
  #     "